"""add columns for available memory

Revision ID: 22d9e9ea0f5b
Revises: 0af35c59602a
Create Date: 2025-05-04 17:41:47.387405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d9e9ea0f5b'
down_revision: Union[str, None] = '0af35c59602a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('available_memory', sa.Float(), nullable=True))
    op.add_column('Users', sa.Column('is_account_pro', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_account_pro')
    op.drop_column('Users', 'available_memory')
    # ### end Alembic commands ###
