"""add_description_for_cells

Revision ID: 8502467ecaf7
Revises: d6aa413bbe64
Create Date: 2025-05-09 13:20:54.801415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8502467ecaf7'
down_revision: Union[str, None] = 'd6aa413bbe64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cells', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cells', 'description')
    # ### end Alembic commands ###
