"""add weight of directory to Cells

Revision ID: d6aa413bbe64
Revises: 22d9e9ea0f5b
Create Date: 2025-05-04 18:08:10.651648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6aa413bbe64'
down_revision: Union[str, None] = '22d9e9ea0f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cells', sa.Column('weight_of_directory', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cells', 'weight_of_directory')
    # ### end Alembic commands ###
